chore(deps): bump golangci-lint@v2.3.1 (#1563)
go get tool
github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.3.1

fixes current issues with the golangci-lint execution:

```text
# github.com/mgechev/revive/formatter
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/friendly.go:134:8: table.SetBorder undefined (type *tablewriter.Table has no field or method SetBorder)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/friendly.go:135:8: table.SetColumnSeparator undefined (type *tablewriter.Table has no field or method SetColumnSeparator)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/friendly.go:136:8: table.SetRowSeparator undefined (type *tablewriter.Table has no field or method SetRowSeparator)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/friendly.go:137:8: table.SetAutoWrapText undefined (type *tablewriter.Table has no field or method SetAutoWrapText)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/friendly.go:138:8: table.AppendBulk undefined (type *tablewriter.Table has no field or method AppendBulk)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/stylish.go:68:9: table.SetBorder undefined (type *tablewriter.Table has no field or method SetBorder)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/stylish.go:69:9: table.SetColumnSeparator undefined (type *tablewriter.Table has no field or method SetColumnSeparator)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/stylish.go:70:9: table.SetRowSeparator undefined (type *tablewriter.Table has no field or method SetRowSeparator)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/stylish.go:71:9: table.SetAutoWrapText undefined (type *tablewriter.Table has no field or method SetAutoWrapText)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/stylish.go:72:9: table.AppendBulk undefined (type *tablewriter.Table has no field or method AppendBulk)
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.9.0/formatter/stylish.go:72:9: too many errors
make: *** [Makefile:90: check] Error 1
Error: Process completed with exit code 2.
```

e.g. [lint-and-test / Lint Golang
(pull_request)](https://github.com/open-component-model/ocm/actions/runs/16723908665/job/47334502210?pr=1562)
- btw. why is this not REQUIRED anymore?

---------

Signed-off-by: Hilmar Falkenberg <hilmar.falkenberg@sap.com>