chore!: migrate to native cobra library (#1504)
<!-- markdownlint-disable MD041 -->
#### What this PR does / why we need it


```
➜ ./bin/ocm install pllug
ocm install — Install New Ocm Cli Components

Synopsis:
  ocm install [<options>] <sub-command> ...

Available Commands:
  plugins     install or update an OCM plugin

Options:
  -h, --help   help for install

Description:
  Install new OCM CLI components
  Use ocm install <command> -h for additional help.


ocm on  remove-cobra-fork [$] via :hamster: v1.24.2
➜ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
ocm on  main [$] via :hamster: v1.24.2
➜ go build -o bin/ocm cmds/ocm/main.go
ocm on  main [$] via :hamster: v1.24.2 took 20s
➜ ./bin/ocm install pllug
Error: unknown command "pllug" for "ocm install"
Run 'ocm install --help' for usage.
ocm on  main [$] via :hamster: v1.24.2
```

#### Which issue(s) this PR fixes
<!--
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
-->

Signed-off-by: Gergely Brautigam <182850+Skarlso@users.noreply.github.com>
Co-authored-by: Jakob Möller <jakob.moeller@sap.com>